
services:
  beatforge:
    build: .
    container_name: bfx_app
    volumes:
      - ./music:/app/music
      - ./data:/app/data
      - ./playlists.txt:/app/playlists.txt:ro
    environment:
      - OUTPUT_DIR=/app/music
      - DATABASE_PATH=/app/data/playlist.db
      - TF_CPP_MIN_LOG_LEVEL=3
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    restart: unless-stopped

